# Generated by Django 2.0 on 2018-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araba', '0003_auto_20180704_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='araba',
            name='foto2',
            field=models.ImageField(blank='True', null='True', upload_to='', verbose_name='2.FOTOĞRAF'),
        ),
        migrations.AddField(
            model_name='araba',
            name='foto3',
            field=models.ImageField(blank='True', null='True', upload_to='', verbose_name='3.FOTOĞRAF'),
        ),
        migrations.AddField(
            model_name='araba',
            name='foto4',
            field=models.ImageField(blank='True', null='True', upload_to='', verbose_name='4.FOTOĞRAF'),
        ),
        migrations.AddField(
            model_name='araba',
            name='foto5',
            field=models.ImageField(blank='True', null='True', upload_to='', verbose_name='5.FOTOĞRAF'),
        ),
        migrations.AlterField(
            model_name='araba',
            name='foto1',
            field=models.ImageField(blank='True', null='True', upload_to='', verbose_name='1.FOTOĞRAF(VİTRİN)'),
        ),
        migrations.AlterField(
            model_name='araba',
            name='modeli',
            field=models.IntegerField(default=2018, verbose_name='MODEL YILI'),
        ),
    ]
