# Generated by Django 2.0 on 2018-07-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araba', '0004_auto_20180705_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='araba',
            options={'ordering': ['-ilantarihi']},
        ),
        migrations.AddField(
            model_name='araba',
            name='kilometre',
            field=models.IntegerField(default=0, verbose_name='KİLOMETRE'),
        ),
        migrations.AddField(
            model_name='araba',
            name='renk',
            field=models.CharField(default='', max_length=25, verbose_name='RENK'),
        ),
        migrations.AddField(
            model_name='araba',
            name='silindirhacmi',
            field=models.IntegerField(default=1000, verbose_name='SİLİNDİR HACMİ'),
        ),
        migrations.AddField(
            model_name='araba',
            name='vites',
            field=models.CharField(choices=[('manuel', 'MANUEL'), ('otomatik', 'OTOMATİK')], default='manuel', max_length=15, verbose_name='VİTES TİPİ'),
        ),
        migrations.AddField(
            model_name='araba',
            name='yakit',
            field=models.CharField(choices=[('benzin', 'BENZİN'), ('lpg', 'LPG/BENZİN'), ('dizel', 'DİZEL'), ('hibrit', 'HİBRİT')], default='benzin', max_length=15, verbose_name='YAKIT TÜRÜ'),
        ),
    ]
