# Generated by Django 2.0 on 2018-07-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araba', '0005_auto_20180710_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='araba',
            name='fiyat',
            field=models.IntegerField(default=0, verbose_name='FİYAT(TL)'),
        ),
    ]
