# Generated by Django 2.0 on 2018-07-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araba', '0006_araba_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='araba',
            name='vites',
            field=models.CharField(choices=[('MANUEL', 'MANUEL'), ('OTOMATİK', 'OTOMATİK')], default='manuel', max_length=15, verbose_name='VİTES TİPİ'),
        ),
        migrations.AlterField(
            model_name='araba',
            name='yakit',
            field=models.CharField(choices=[('BENZİN', 'BENZİN'), ('LPG/BENZİN', 'LPG/BENZİN'), ('DİZEL', 'DİZEL'), ('HİBRİT', 'HİBRİT')], default='benzin', max_length=15, verbose_name='YAKIT TÜRÜ'),
        ),
    ]
